dist: bionic
os:
  - linux
services:
  - docker
  - xvfb
language: node_js
node_js:
  - "12.14.0"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
# Install Chrome
addons:
  apt:
    packages:
      - dpkg
  chrome: stable
before_install:
  - npm i -g @angular-devkit/schematics-cli @angular/cli@9.0.0-rc.10 @vue/cli ionic codecov react-native-cli
install:
  - npm ci
  - ng --version
script:
  - set -e
  - npm run build
  - npm test && npm run coverage
  # create apps and confirm tests still pass
  - ./test-all.sh
after_success:
  - codecov
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
